name: TaupeGun
main: me.mathdu07.taupegun.TGPlugin
version: 1.1

commands:
   taupegun:
      description: Taupe Gun
      usage: "Usage : /<command> <start|shift|team|addspawn|generatewalls|pause>"
      aliases: [tg]
   t:
      description: "Chat spécial pour les taupes"
      usage: "Usage : /<command> <message>"
   reveal:
      description: "Révéle la taupe"
      usage: "Usage : /<command>"
   claim:
      description: "Permet d'obtenir un kit pour une taupe"
      usage: "Usage : /<command>"
