name: TaupeGun
main: me.mathdu07.taupegun.TGPlugin
version: 0.1

commands:
   taupegun:
      description: Taupe Gun
      usage: "Usage : /<command> <start|shift|team|addspawn|generatewalls>"
      aliases: [tg]
